"""empty message

Revision ID: 29414ac9e384
Revises: eee414b5993e
Create Date: 2021-02-13 15:26:48.412156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29414ac9e384'
down_revision = 'eee414b5993e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likepost', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likepost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
