"""empty message

Revision ID: eee414b5993e
Revises: 996332f6f12f
Create Date: 2021-02-13 15:25:38.775667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee414b5993e'
down_revision = '996332f6f12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likepost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likepost', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
